name: synthesis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - ffmpeg=4.3.1
  - sox=14.4.2
  - fluidsynth=v1.1.11
  - pip=21.1.3
  - numpy=1.21.0
  - scipy=1.7.0
  - matplotlib=3.4.2
  - tqdm=4.61.2
  - librosa=0.8.1
  - music21=6.7.1
  - pip:
    - muspy=0.3.0
  - pylint
  - black
  - flake8
